---
 - name: Install packages and update
   hosts: tag_PartOf_FinalProject
   remote_user: ec2-user
   become: true

   tasks:
     - name: Install vim
       yum: name=vim state=latest
     - name: Install git
       yum: name=git state=latest
     - name: Install htop
       yum: name=htop state=latest
     - name: Install sysstat
       yum: name=sysstat state=latest 
     - name: upgrade all packages
       yum: name=* state=latest
     - name: Install pip
       yum: name=python-pip state=present
     - name: Install docker pip package
       pip: name=docker
     